---
- name: Set MySQL root password
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_password}}' vtype='password'

- name: Set MySQL root password - confirmation
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_password}}' vtype='password'

- name: Install MySQL
  apt: name={{item}} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: "Copying my.cnf"
  template: src=my.cnf dest="~/.my.cnf" mode=0600
  vars:
    root_db_password: "{{ mysql_password }}"

- name: "Creating mysql.conf.d folder"
  file: path="/etc/mysql/mysql.conf.d" state=directory

- name: "Copying mysql.cfg"
  template: src=mysql.cfg dest="/etc/mysql/mysql.conf.d/mysqld.cnf"

- name: "Start MySQL Service"
  service:
    name: mysql
    state: started
    enabled: true
...
