---
- name: add group
  group:
    name: tomcat
    state: present

- name: add user to tomcat group
  user:
    name: tomcat
    group: tomcat
    home: /opt/tomcat
    shell: /bin/false
  # shell: useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat

- name: download tomcat
  get_url:
    url: http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.28/bin/apache-tomcat-8.5.28.tar.gz
    dest: /tmp/
    mode: u+rwx
- name: create dir to unzip tomcat
  file:
    path: /opt/tomcat
    state: directory
    mode: 0777
  ######no strip function
  # - name: unarchive the tomcat file in tmp
  #   unarchive:
  #     src: /tmp/
  #     dest: /opt/tomcat/
  #     remote_src: True
  #     mode: 0777

- name: create directory and extract archive to it
  shell: cd /tmp && tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1

- name: update permissions
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: 0777
  # shell: cd /opt/tomcat && chgrp -R tomcat /opt/tomcat

- name: give tomcat group access to conf directory
  shell: cd /opt/tomcat && chmod -R g+r conf && chmod g+x conf

- name: make tomcat user owner of various dirs
  shell: cd /opt/tomcat && chown -R tomcat webapps/ work/ temp/ logs/ /opt/tomcat

- name: copy tomcat.service file
  template:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service

- name: reload system daemon
  shell: systemctl daemon-reload && systemctl start tomcat

# - name: check status of daemon
#   shell: systemctl status tomcat

- name: allow tomcat port acsess to 8080
  shell: ufw allow 8080

- name: start tomcat
  shell: systemctl enable tomcat

- name: "Setting up user for Apache Tomcat"
  template: src=apache_template.xml.j2 dest=/opt/tomcat/conf/tomcat-users.xml
  become: yes

- name: restart tomcat
  shell: systemctl restart tomcat

...









#
# - name: "Download Apache Tomcat 8.0 Archive"
#   get_url:
#     url:  http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.28/bin/apache-tomcat-8.5.28.tar.gz
#     dest: /usr/local
#     force: no
#   become: yes
#
# - name: "Unzipping Apache Tomcat Archive"
#   unarchive:
#     src: /usr/local/apache-tomcat-8.5.28.tar.gz
#     dest: /usr/local/
#     remote_src: yes
#   become: yes
# - name: add user to tomcat group
#   user:
#     name: tomcat
#     group: tomcat
#     home: /usr/local
#     shell: /bin/false
# - name: "Removing previous Apache Tomcat instances"
#   file:
#     path: /usr/local/tomcat8
#     state: absent
#   become: true
#
# - name: "Renaming Apache Tomcat Directory"
#   command: mv /usr/local/apache-tomcat-8.5.28 /usr/local/tomcat8
#   become: yes
#
# - name: "Setting up user for Apache Tomcat"
#   template: src=apache_template.xml.j2 dest=/usr/local/tomcat8/conf/tomcat-users.xml
#   become: yes
#
# # - name: "Setting up Apache Tomcat Variables"
# #   shell: echo "export CATALINA_HOME="{{apache_install_location}}/tomcat8"" >> /etc/environment
# #   become: yes
# # - shell: echo "export JAVA_HOME="/usr/lib/jvm/java-8-oracle"" >> /etc/environment
# #   become: yes
# # - shell: echo "export JRE_HOME="/usr/lib/jvm/java-8-oracle/jre"" >> /etc/environment
# #   become: yes
#
# - name: "Starting Apache server"
#   command: nohup /usr/local/tomcat8/bin/startup.sh
#   become: yes
