---
- name: Configure Jenkins Server
  hosts: jenkins
  become: yes
  vars:
    JENKINS_USER: "{{ lookup('env','JENKINS_USER') }}"
    JENKINS_PASSWORD: "{{ lookup('env','JENKINS_PASSWORD') }}"
  tasks:
    - name: install PIP
      apt:
        cache_valid_time: 3600
        name: python-pip
        state: latest
    - name: install jjb using python2
      apt:
        cache_valid_time: 3600
        name: python-jenkins-job-builder
        state: latest
    - name: install jjb using PIP
      pip:
        name: jenkins-job-builder
        state: latest
    - shell: pip install --upgrade jenkins-job-builder
    - name: create jenkins jobs folder
      file:
        path: /etc/jenkins_jobs
        state: directory
        mode: 0777
    - name: copy ini file to the directory
      template:
        src: templates/jenkins_jobs.ini
        dest: /etc/jenkins_jobs/
    - name: make jobs directory
      file:
        path: jobs
        state: directory
        mode: 0777


    - name: create itrust job builder file
      template:
        src: templates/itrust-jjb.yaml
        dest: jobs/
    - name: create checkbox job builder file
      template:
        src: templates/checkbox-jjb.yaml
        dest: jobs/
    - name: create checkbox post build job builder file
      template:
        src: templates/ansible-checkbox-jjb.yaml
        dest: jobs/

    - name: create itrust post build job builder file
      template:
        src: templates/ansible-itrust-jjb.yaml
        dest: jobs/

    - name: run the jenkins-jobs
      shell: jenkins-jobs update jobs
      args:
        chdir: "/root"
    - name: test the running of the jobs
      shell: jenkins-jobs test jobs

    - name: get jenkins crumb
      shell: curl -s 'http://{{JENKINS_USER}}:{{JENKINS_PASSWORD}}@localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
      register: crumb

    - debug: var=crumb
    - name: run itrust2 job
      shell: curl -X POST http://{{JENKINS_USER}}:{{JENKINS_PASSWORD}}@localhost:8080/job/itrust2/build -H "{{crumb.stdout}}"
      register: result
    - debug: var=result.stdout

    - name: run itrust2 job
      shell: curl -X POST http://{{JENKINS_USER}}:{{JENKINS_PASSWORD}}@localhost:8080/job/checkbox/build -H "{{crumb.stdout}}"
      register: result
    - debug: var=result.stdout
...
