---
- name: stop services
#  hosts: 138.68.248.226
  become: yes
  hosts: "{{ groups['checkbox'] | random }}"
  gather_facts: False
  tasks:
    # - name: Restart nginx server
    #   shell: service nginx restart
    - name: restart mongodb server
      shell: service mongod stop
...
