---
- name: Import public MongoDB key
  become: yes
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
    state: present

- name: Add MongoDB source list
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"
    filename: "mongodb-org-3.6"
    state: present
    update_cache: yes

- name: Install MongoDB
  become: yes
  apt:
    name: "mongodb-org"
    state: latest

- name: Create data directory for MongoDB
  become: yes
  file:
    path: /data/db
    state: directory
    mode: 755

- name: Install python-setuptools
  become: yes
  apt:
    name: python-setuptools
    state: present

- name: Install pymongo
  become: yes
  shell: "easy_install pymongo"

# If things don't work, try restarting the MongoDB service.
- name: Reload MongoDB Service
  become: yes
  service:
    name: mongod
    state: started
  # shell: service mongod start

- name: Add new user to MongoDB Administrator Database
  become: yes
  mongodb_user:
    database: "admin"
    name: "{{ lookup('env', 'MONGO_USER') }}"
    password: "{{ lookup('env', 'MONGO_PASSWORD') }}"
    state: present
...
