apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkbox-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: checkbox
  template:
    metadata:
      labels:
        app: checkbox
    spec:
      containers:
      - name: nginx
        image: ssgodbol/checkboxio_nginx
        ports:
        - containerPort: 80
      - name: node
        image: ssgodbol/checkboxio_node
        env:
        - name: MONGO_IP
          value: {{ jenkins_ip }}
