---
- hosts: localhost
  connection: localhost

  roles:
    - "createDroplet"

- hosts: nodes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  
  roles:
    - "installJenkins"
    - "configureJenkins"
...