---
- name: Install Prerequisites
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - git
    - maven
    - build-essential
    - default-jre
    - default-jdk
    - curl

- name: Add Jenkins key
  become: yes
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
    state: present

- name: Add Jenkins repo
  become: yes
  copy: content="deb http://pkg.jenkins.io/debian-stable binary/" dest="/etc/apt/sources.list.d/jenkins.list"
  update_cache: yes

- name: Install Jenkins
  become: yes
  apt:
    name: jenkins
    state: installed 
    update_cache: yes
    force: yes
  register: jenkins_install
...