---
- hosts: checkbox
  gather_facts: False
  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: yes
  
  roles:
    - nodejs
    - nginx
    - mongodb

  tasks:
    - name: Setting up variables
      set_fact:
        MONGO_PORT: "{{ lookup('env', 'MONGO_PORT') }}"
        MONGO_IP: "{{ lookup('env', 'MONGO_IP') }}"
        MONGO_USER: "{{ lookup('env', 'MONGO_USER') }}"
        MONGO_PASSWORD: "{{ lookup('env', 'MONGO_PASSWORD') }}"
        MAIL_USER: "{{ lookup('env', 'MAIL_USER') }}"
        MAIL_PASSWORD: "{{ lookup('env', 'MAIL_PASSWORD') }}"
        MAIL_SMTP: "{{ lookup('env', 'MAIL_SMTP') }}"

    - name: Clone git repo
      git:
        repo: "https://github.com/chrisparnin/checkbox.io.git"
        dest: "~/checkbox.io"
        clone: yes
        update: yes
    
    # - name: Install node modules for checkbox.io
    #   shell: "npm install"
    #   args:
    #     chdir: "/home/vagrant/checkbox.io/server-side/site/"
    
    # - name: Install forever
    #   shell: "npm install forever -g"
    #   args:
    #     chdir: "/home/vagrant/checkbox.io/server-side/site/"
    
    # - name: Run Checkbox.io
    #   shell: "forever start server.js"
    #   args:
    #     chdir: "/home/vagrant/checkbox.io/server-side/site/"
...