---
- name: Install Prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - maven
    - build-essential
  become: yes

- name: install java
  become: yes
  apt:
    name: default-jre
    state: latest
    update_cache: yes

- name: Add Jenkins Repo Key
  become: yes
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present
    validate_certs: no

- name: Add Jenkins Source List
  become: yes
  copy: content="deb http://pkg.jenkins.io/debian-stable binary/" dest="/etc/apt/sources.list.d/jenkins.list"
    
- name: Install Jenkins
  become: yes
  apt:
    name: jenkins    
    state: present
    update_cache: yes
  register: install_jenkins