---
- name: Download Google Chrome
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /google-chrome.deb
    mode: u+rwx

- name: Install Google Chrome
  apt:
    deb: /google-chrome.deb
