---

- name: Set github name and email
  shell: git config --global user.email '{{GIT_EMAIL}}' && git config --global user.name '{{GIT_NAME}}'

- name: Create fuzz directory
  shell: mkdir /fuzz

- name: Copying fuzzer.js to jenkins server
  template: src=fuzzer.js dest="/fuzz/"

- name: Copy package.json to jenkins server
  template: src=package.json dest="/fuzz/"

- name: Perform npm install
  npm:
    path: /fuzz
    state: latest

- name: git checkout fuzzer
  shell: cd /iTrust2-v2 && git branch fuzzer && git checkout fuzzer

- name: Copy pom file to itrust repo
  template:
    src: templates/pom.xml
    dest: /iTrust2-v2/iTrust2/

- name: git commit update pom.xml
  shell: cd /iTrust2-v2 && git add . && git commit -m "Updated pom.xml"

- name: Run fuzzer.js
  shell: node /fuzz/fuzzer.js
...