---
- name: Provision iTrust Server on Digital Ocean
  hosts: localhost
  connection: localhost
  tasks:
  - name: creating 5 instances
    with_items:
      - "itrust1"
      - "itrust2"
      - "itrust3"
      - "itrust4"
      - "itrust5"
    include_role:
      name: droplet_itrust
    vars:
      NODE_GROUP: "itrust"
      NODE_NAME: "{{ item }}"
      DOTOKEN: "{{ lookup('env','DOTOKEN') }}"

- hosts: itrust
  become: yes
  gather_facts: no

  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson

  vars:
    - mysql_pass: "{{ lookup('env','MYSQL_PASSWORD') }}"
    - gmail_pass: "{{ lookup('env','MAIL_PASSWORD') }}"
    - gmail_user: "{{ lookup('env','MAIL_USER') }}"
    - git_token: "{{ lookup('env', 'GIT_TOKEN') }}"
    - jenkins_ip: "{{ lookup('env', 'JENKINS_IP') }}"

  roles:
    # - role: mysql
    #   mysql_pass: "{{ lookup('env','MYSQL_PASSWORD') }}"
    - java8

  tasks:
    - name: Install Maven
      apt: name=maven state=latest update_cache=yes

    - name: Clone iTrust Repository
      git:
        repo: "https://{{git_token}}@github.ncsu.edu/ubhosle/iTrust2-v2.git"
        dest: "~/iTrust2-v2"
        clone: yes

    - name: copy db.properties file
      copy:
        src: ~/iTrust2-v2/iTrust2/src/main/java/db.properties.template
        dest: ~/iTrust2-v2/iTrust2/src/main/java/db.properties
        remote_src: True

    - name: Set the password in db file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/db.properties
        regexp: 'password'
        line: 'password {{mysql_pass}}'

    - name: Set the IP-Address in db file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/db.properties
        regexp: 'url'
        line: 'url jdbc:mysql://{{jenkins_ip}}:3306/iTrust2?createDatabaseIfNotExist=true'

    - name: Copy hibernate file
      copy:
        src: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties.template
        dest: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        remote_src: True

    - name: Set the IP-Address in hibernate file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        regexp: 'url'
        line: 'hibernate.connection.url = jdbc:mysql://{{jenkins_ip}}:3306/iTrust2?createDatabaseIfNotExist=true'

    - name: Set the password in hibernate file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        regexp: 'hibernate.connection.password'
        line: 'hibernate.connection.password = {{mysql_pass}}'

    - name: Set password for email.properties
      copy:
        src: ~/iTrust2-v2/iTrust2/src/main/java/email.properties.template
        dest: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        remote_src: True

    - name: set the username to root in email.properties
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'username'
        line: 'username root'

    - name: Set username in email.properties
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'from'
        line: 'from {{gmail_user}}'

    - name: Set email username
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'username'
        line: 'username {{gmail_user}}'

    - name: Set email password
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'password'
        line: 'password {{gmail_pass}}'

    - name: Set the IP-Address in DBUtil.java file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/edu/ncsu/csc/itrust2/utils/DBUtil.java
        regexp: '.setUrl\( null == url \? "jdbc:mysql://localhost:3306/iTrust2\?createDatabaseIfNotExist=true" : url \);'
        line: '.setUrl( null == url ? "jdbc:mysql://{{jenkins_ip}}:3306/iTrust2?createDatabaseIfNotExist=true" : url );'

    - name:  Build iTrust2
      shell: cd ~/iTrust2-v2/iTrust2/ && mvn process-test-classes -f pom-data.xml

    - name: Run iTrust2
      shell: cd ~/iTrust2-v2/iTrust2/ && ((nohup mvn jetty:run) &)

- name: Monitoring on iTrust
  hosts: localhost
  connection: localhost
  vars:
    - jenkins_ip: "{{ lookup('env','JENKINS_IP') }}"
  tasks:
    - name: git clone ItrustMonitoring
      git:
        repo: "https://github.com/pushpendrasp/ItrustMonitoring.git"
        dest: "/ItrustMonitoring/"
        clone: yes

    - name: install http-server inside ItrustMonitoring
      shell: npm install http-server -g
      args:
        chdir: "/ItrustMonitoring/www/"
  
    - name: Change the socket ip
      lineinfile:
        path: /ItrustMonitoring/www/statusModel.js
        regexp: 'var socket = io.connect\("http://localhost:3000"\);'
        line: 'var socket = io.connect("http://{{ jenkins_ip }}:3000");'

    - name: Install forever
      shell: "npm install forever -g"
      args:
        chdir: "/ItrustMonitoring/"

    # - name: Run http-server
    #   shell: "forever start $(which http-server) /ItrustMonitoring/www/"
    #   args:
    #     chdir: "/ItrustMonitoring/www/"

    # - name: Run Monitoring
    #   shell: "forever start main.js"
    #   args:
    #     chdir: "/ItrustMonitoring"
...
