---
- hosts: itrust
  become: yes
  gather_facts: no
  serial: 1

  vars:
    - mysql_pass: "{{ lookup('env','MYSQL_PASSWORD') }}"
    - gmail_pass: "{{ lookup('env','MAIL_PASSWORD') }}"
    - gmail_user: "{{ lookup('env','MAIL_USER') }}"
    - git_token: "{{ lookup('env', 'GIT_TOKEN') }}"
    - jenkins_ip: "{{ lookup('env', 'JENKINS_IP') }}"


  tasks:
    - name: Stop Service
      shell: sudo kill `sudo lsof -t -i:8080`
      ignore_errors: yes

    - name: copy itrust from production to server
      copy:
        src: "/deploy/production-www/"
        dest: "~/iTrust2-v2/"
        mode: 0777
        directory_mode: yes

    - name: copy db.properties file
      copy:
        src: ~/iTrust2-v2/iTrust2/src/main/java/db.properties.template
        dest: ~/iTrust2-v2/iTrust2/src/main/java/db.properties
        remote_src: True

    - name: Set the password in db file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/db.properties
        regexp: 'password'
        line: 'password {{mysql_pass}}'

    - name: Set the IP-Address in db file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/db.properties
        regexp: 'url'
        line: 'url jdbc:mysql://{{jenkins_ip}}:3306/iTrust2?createDatabaseIfNotExist=true'

    - name: Copy hibernate file
      copy:
        src: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties.template
        dest: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        remote_src: True

    - name: Set the IP-Address in hibernate file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        regexp: 'url'
        line: 'hibernate.connection.url = jdbc:mysql://{{jenkins_ip}}:3306/iTrust2?createDatabaseIfNotExist=true'

    - name: Set the password in hibernate file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        regexp: 'hibernate.connection.password'
        line: 'hibernate.connection.password = {{mysql_pass}}'

    - name: Set password for email.properties
      copy:
        src: ~/iTrust2-v2/iTrust2/src/main/java/email.properties.template
        dest: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        remote_src: True

    - name: set the username to root in email.properties
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'username'
        line: 'username root'

    - name: Set username in email.properties
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'from'
        line: 'from {{gmail_user}}'

    - name: Set email username
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'username'
        line: 'username {{gmail_user}}'

    - name: Set email password
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/email.properties
        regexp: 'password'
        line: 'password {{gmail_pass}}'

    - name: Set the IP-Address in DBUtil.java file
      lineinfile:
        path: ~/iTrust2-v2/iTrust2/src/main/java/edu/ncsu/csc/itrust2/utils/DBUtil.java
        regexp: '.setUrl\( null == url \? "jdbc:mysql://localhost:3306/iTrust2\?createDatabaseIfNotExist=true" : url \);'
        line: '.setUrl( null == url ? "jdbc:mysql://{{jenkins_ip}}:3306/iTrust2?createDatabaseIfNotExist=true" : url );'

    - name: Run iTrust2
      shell: cd ~/iTrust2-v2/iTrust2/ && ((nohup mvn jetty:run) &)

    - name: Wait droplet to come online
      pause:
        seconds: 50

...
