---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Install Python2
      raw: apt-get -y install python-simplejson
      become: yes

    - name: Install pip
      apt:
        name: python-pip
        force: yes
        update_cache: yes

    - name: Install dopy
      become: yes
      raw: pip install 'dopy>=0.3.5,<=0.3.5'

  roles:
    - docker
    - kubernetes-common
    - env-variables

- hosts: kube-master
  tasks:
    - name: Generate Kubernetes token
      shell: kubeadm token generate
      register: kubeadm_token

    - name: Output Kubernetes token
      debug:
        var: kubeadm_token.stdout

- hosts: kube-master
  roles:
    - { role: kubernetes-master, token: "5fowpv.gn0hj7n963hltq4u" }

- hosts: kube-nodes
  roles:
    # - mongodb
    - { role: kubernetes-nodes, token: "5fowpv.gn0hj7n963hltq4u", master_ip: "{{master}}"}
...