---

- name: Provision Kubernetes nodes on Digital Ocean
  hosts: localhost
  connection: localhost
  tasks:
  - name: Create nodes for kubernetes cluster
    with_items:
      - "kubenode1"
      - "kubenode2"
      - "kubenode3"
    include_role:
      name: droplet
    vars:
      NODE_GROUP: "kubenodes"
      NODE_NAME: "{{ item }}"
      DOTOKEN: "{{ lookup('env','DOTOKEN') }}"
      

- hosts: localhost:kubenodes
  gather_facts: no
  pre_tasks:
    - name: Install Python2
      raw: apt-get -y install python-simplejson
      become: yes

    - name: Install pip
      become: yes
      apt:
        name: python-pip
        force: yes
        update_cache: yes

    - name: Install dopy
      become: yes
      raw: pip install 'dopy>=0.3.5,<=0.3.5'

  roles:
    - docker
    - kubernetes-common
    - env-variables

# - hosts: kube-master
#   tasks:
#     - name: Generate Kubernetes token
#       shell: kubeadm token generate
#       register: kubeadm_token

#     - name: Output Kubernetes token
#       debug:
#         var: kubeadm_token.stdout

- hosts: localhost
  roles:
    - mongodb
    - { role: kubernetes-master, token: "5fowpv.gn0hj7n963hltq4u" }

- hosts: kubenodes
  roles:
    - mongodb
    - { role: kubernetes-nodes, token: "5fowpv.gn0hj7n963hltq4u", master_ip: "192.168.33.100"}

- hosts: localhost
  tasks:
    - name: Start deployment
      shell: kubectl create -f /files/podsetup.yml

    - name: Expose application
      shell: kubectl expose deployment checkbox-deployment --type="LoadBalancer" --port 80

    - name: Saving exposed port number
      shell: export NODE_PORT=$(kubectl get services/checkbox-deployment -o go-template='{{(index .spec.ports 0).nodePort}}') && echo $NODE_PORT
      register: port

    - name: Port number
      debug:
        var: port
...