---
- name: Provision Kubernetes nodes on Digital Ocean
  hosts: localhost
  connection: localhost
  tasks:
  - name: Create nodes for kubernetes cluster
    with_items:
      - "kubenode1"
      - "kubenode2"
      - "kubenode3"
    include_role:
      name: droplet
    vars:
      NODE_GROUP: "kubenodes"
      NODE_NAME: "{{ item }}"
      DOTOKEN: "{{ lookup('env','DOTOKEN') }}"

- name: Provision Kubernetes master on Digital Ocean
  hosts: localhost
  connection: localhost
  tasks:
  - name: Create nodes for kubernetes cluster
    include_role:
      name: droplet
    vars:
      NODE_GROUP: "kubemaster"
      NODE_NAME: "kubemaster"
      DOTOKEN: "{{ lookup('env','DOTOKEN') }}"


- hosts: kubemaster
  gather_facts: no
  pre_tasks:
    - name: Install Python2
      raw: apt-get -y install python-simplejson
      become: yes

    - name: Install pip
      become: yes
      apt:
        name: python-pip
        force: yes
        update_cache: yes

    - name: Install dopy
      become: yes
      raw: pip install 'dopy>=0.3.5,<=0.3.5'

  roles:
    - { role: redis, redis_ip: "{{ lookup('env','kubemaster') }}" }
    - docker
    - kubernetes-common
    
  tasks:
    - name: Podsetup.yml
      template:
        src: /files/kubernetes/podsetup.yml
        dest: "~/podsetup.yml"
      vars:
        mongo_ip: "{{ lookup('env','kubemaster') }}"
        redis_ip: "{{ lookup('env','kubemaster') }}"

- hosts: kubenodes
  gather_facts: no
  pre_tasks:
    - name: Install Python2
      raw: apt-get -y install python-simplejson
      become: yes

    - name: Install pip
      become: yes
      apt:
        name: python-pip
        force: yes
        update_cache: yes

    - name: Install dopy
      become: yes
      raw: pip install 'dopy>=0.3.5,<=0.3.5'

  roles:
    - docker
    - kubernetes-common

- hosts: kubemaster
  roles:
    - { role: mongodb, mongo_ip: "{{ lookup('env','kubemaster') }}" }
    - { role: kubernetes-master, token: "{{ lookup('env','kubetoken') }}" }

- hosts: kubenodes
  roles:
    - { role: kubernetes-nodes, token: "{{ lookup('env','kubetoken') }}", master_ip: "{{ lookup('env','kubemaster') }}"}

- hosts: kubemaster
  tasks:
    - name: Start deployment
      shell: kubectl create -f ~/podsetup.yml

    - name: Expose application
      shell: kubectl expose deployment checkbox-deployment --type="LoadBalancer" --port 80
...